version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_EMBEDDEDDATABASE_ENABLED=true
      - SONAR_FORCEAUTHENTICATION=false
